app:
  image: 018789814334.dkr.ecr.ap-southeast-2.amazonaws.com/vprofileappimg
  tag: d79d10b
  replicas: 1
  containerPort: 8080
  servicePort: 8080
  defaultUser: ""
db:
  image: vprofilecontainers/vprofiledb
  tag: latest
  replicas: 1
  containerPort: 3306
  servicePort: 3306
  storageClass: gp2
  storageSize: 3Gi
  defaultUser: root
memcached:
  image: memcached
  tag: latest
  replicas: 1
  containerPort: 11211
  servicePort: 11211
  defaultUser: ""
rabbitmq:
  image: rabbitmq
  tag: latest
  replicas: 1
  containerPort: 5672
  servicePort: 5672
  defaultUser: guest
initcontainers:
  image: busybox
  commands:
    - until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;
    - until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for cache; sleep 2; done;
    - until nslookup vpromq-01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for rmq; sleep 2; done;
ingress:
  enabled: false
  host: vprofile.example.com
  servicePort: 8080
secrets:
  dbPassword: dbpassword
  rmqPassword: guest
dockerregistry:
  enabled: false
  server: ""
  username: ""
  password: ""
  email: ""
