apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
{{- if .Values.dockerregistry.enabled }}
      imagePullSecrets:
        - name: dockerregistry-secret
{{- end }}
      containers:
      - name: vprodb
        image: {{ .Values.db.image }}:{{ .Values.db.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: mysql
          containerPort: {{ .Values.db.containerPort }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-pv-claim
