{{- if .Values.dockerregistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerregistry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.dockerregistry.server }}": {
          "username": "{{ .Values.dockerregistry.username }}",
          "password": "{{ .Values.dockerregistry.password }}",
          "email": "{{ .Values.dockerregistry.email }}",
          "auth": "{{ printf "%s:%s" .Values.dockerregistry.username .Values.dockerregistry.password | b64enc }}"
        }
      }
    }
{{- end }}
